url: "" # the base hostname & protocol for your site, e.g. http://hexad.de
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

kramdown:
  syntax_highlighter: rouge
  input: GFM

collections:
  expertise:
    output: false
  expertisecontent:
    output: true
  clients:
    output: false
  works:
    output: false
  socialcommitments:
    output: false

exclude:
  [nbproject, yarn.lock, package.json, package-lock.json, gitlab-ci.yml, public]
